### ISSUE TITLE
Enable dependabot tracking and add CI tests for the Dockerfile

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#1883]
Since using the `:latest` label on the build and run time base images in the Dockerfile is dangerous (see #1746 and #1781), being able to use a specific tested version of the images is important.  Dependabot support tracking the images in use in a Dockerfile and creating a PR when never versions are available.  Also, since sometimes a problem with the build doesn't surface until the on-merge actions are run, CI specifically for the Dockerfile should be implemented.

Things to do:
  - Enable dependabot on the Dockerfile.  Multiple ecosystems are allowed in the config, so this style is allowable:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@patternfly/*"
        dependency-type: "direct"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
```

  - Based on the on-merge workflow [image-build.yaml](https://github.com/konveyor/tackle2-ui/blob/main/.github/workflows/image-build.yaml) that builds the images and uploads to a repo, create an action:
    - If the Dockerfile has been touched, execute.  Else, skip.
    - Run the image build with the same settings as the multiarch build, but don't push to a repo
    - Pass CI on a Dockerfile change when the image builds all successfully complete (in the github action environment)
