### ISSUE TITLE
[BUG] Failed to run tech-discovery and analyzer tasks on Konveyor-0.6.0-rc.2

### ISSUE THREAD

**Issue by mguetta1** [konveyor/tackle2-ui#2175]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

0.6.0-rc.2

### Priority

Critical

### Current Behavior

analyzer task details:
```
id: 3
createUser: admin.noauth
createTime: 2025-01-23T09:45:53.722697887Z
name: book-server.1.windup
kind: analyzer
addon: analyzer
extensions:
    - java
state: Failed
priority: 10
data:
    mode:
        artifact: ""
        binary: false
        withDeps: true
    rules:
        labels:
            excluded: []
            included:
                - konveyor.io/target=cloud-readiness
        path: ""
        tags:
            excluded: []
    scope:
        packages:
            excluded: []
            included: []
        withKnownLibs: false
    sources: []
    tagger:
        enabled: true
    targets: []
    verbosity: 0
application:
    id: 1
    name: book-server
bucket:
    id: 4
    name: ""
pod: konveyor-tackle/task-3-t2s9d
started: 2025-01-23T09:45:54.262552508Z
terminated: 2025-01-23T09:45:58.555259583Z
events:
    - kind: AddonSelected
      count: 1
      last: 2025-01-23T09:45:54.230877412Z
    - kind: ExtensionSelected
      count: 1
      reason: java
      last: 2025-01-23T09:45:54.262545425Z
    - kind: PodCreated
      count: 1
      reason: konveyor-tackle/task-3-t2s9d
      last: 2025-01-23T09:45:54.306628911Z
    - kind: PodPending
      count: 4
      reason: ContainerCreating
      last: 2025-01-23T09:45:56.425462956Z
    - kind: PodPending
      count: 1
      reason: ErrImagePull
      last: 2025-01-23T09:45:57.497860683Z
    - kind: PodRunning
      count: 1
      last: 2025-01-23T09:45:57.497862206Z
    - kind: ImageError
      count: 1
      reason: ImagePullBackOff
      last: 2025-01-23T09:45:58.555260064Z
    - kind: ContainerKilled
      count: 1
      reason: 'container: ''addon'' had not terminated.'
      last: 2025-01-23T09:45:58.690254451Z
errors:
    - severity: Error
      description: 'Container (java) failed: ImagePullBackOff'
activity:
    - 'OptDir:    /addon/opt'
    - 'SharedDir: /shared'
    - 'CacheDir:  /cache'
    - 'SourceDir: /shared/source'
    - 'RuleDir:   /addon/rules'
    - 'BinDir:    /shared/bin'
    - 'M2Dir:     /cache/m2'
    - Fetching application.
    - '[CMD] Running: /usr/bin/ssh-agent -a /tmp/agent.1'
    - '[CMD] /usr/bin/ssh-agent succeeded.'
    - '[SSH] Agent started.'
    - '[GIT] Cloning: https://github.com/ibraginsky/book-server'
    - '[FILE] Created /addon/.gitconfig.'
    - '[CMD] Running: /usr/bin/git clone --depth 1 https://github.com/ibraginsky/book-server /shared/source/book-server'
    - '[CMD] /usr/bin/git succeeded.'
    - '[RULESET] fetching: id=1 (.discovery)'
    - '[RULESET] fetching: id=24 (cloud-readiness)'
    - '[RULESET] fetching (dep): id=20 (.technology-usage)'
    - '[CMD] Running: /usr/bin/windup-shim convert --outputdir /addon/rules/rulesets/1/rules /addon/rules/rulesets/1/rules'
    - '[CMD] /usr/bin/windup-shim succeeded.'
    - '[CMD] Running: /usr/bin/windup-shim convert --outputdir /addon/rules/rulesets/24/rules /addon/rules/rulesets/24/rules'
    - '[CMD] /usr/bin/windup-shim succeeded.'
    - '[CMD] Running: /usr/bin/windup-shim convert --outputdir /addon/rules/rulesets/20/rules /addon/rules/rulesets/20/rules'
    - '[CMD] /usr/bin/windup-shim succeeded.'
    - '[CMD] Running: /usr/local/bin/konveyor-analyzer --provider-settings /addon/opt/settings.yaml --output-file /addon/issues.yaml --dep-output-file /addon/deps.yaml --rules /addon/rules/rulesets/1/rules --rules /addon/rules/rulesets/24/rules --rules /addon/rules/rulesets/20/rules --label-selector konveyor.io/target=cloud-readiness --dep-label-selector !konveyor.io/dep-source=open-source'
attached:
    - id: 347
      name: ssh-agent.output
      activity: 9
    - id: 348
      name: git.output
      activity: 14
    - id: 351
      name: windup-shim.output
      activity: 19
    - id: 352
      name: windup-shim.output
      activity: 21
    - id: 353
      name: windup-shim.output
      activity: 23
    - id: 354
      name: settings.yaml
      activity: 24
    - id: 355
      name: konveyor-analyzer.output
      activity: 25
    - id: 356
      name: pod.yaml
    - id: 357
      name: addon.log
```

tech-discovery task details:
```
id: 2
createTime: 2025-01-23T09:45:43.34863008Z
name: book-server-tech-discovery
kind: tech-discovery
addon: tech-discovery
extensions:
    - discovery-java
state: Failed
data:
    mode:
        discovery: true
    rules:
        labels:
            included:
                - discovery
    tagger:
        enabled: true
        source: tech-discovery
application:
    id: 1
    name: book-server
bucket:
    id: 3
    name: ""
pod: konveyor-tackle/task-2-qckds
started: 2025-01-23T09:45:47.850004277Z
terminated: 2025-01-23T09:46:08.186718866Z
events:
    - kind: AddonSelected
      count: 1
      last: 2025-01-23T09:45:43.486925879Z
    - kind: ExtensionSelected
      count: 1
      reason: discovery-java
      last: 2025-01-23T09:45:43.514745993Z
    - kind: Postponed
      count: 4
      reason: Rule:Dependency matched:2, other:1
      last: 2025-01-23T09:45:46.730586715Z
    - kind: PodCreated
      count: 1
      reason: konveyor-tackle/task-2-qckds
      last: 2025-01-23T09:45:47.909233247Z
    - kind: PodPending
      count: 16
      reason: ContainerCreating
      last: 2025-01-23T09:45:56.43341764Z
    - kind: PodPending
      count: 10
      reason: ErrImagePull
      last: 2025-01-23T09:46:07.132067106Z
    - kind: PodRunning
      count: 10
      last: 2025-01-23T09:46:07.132069511Z
    - kind: ImageError
      count: 1
      reason: ImagePullBackOff
      last: 2025-01-23T09:46:08.186719117Z
    - kind: ContainerKilled
      count: 1
      reason: 'container: ''addon'' had not terminated.'
      last: 2025-01-23T09:46:08.302435836Z
errors:
    - severity: Error
      description: 'Container (discovery-java) failed: ImagePullBackOff'
activity:
    - 'OptDir:    /addon/opt'
    - 'SharedDir: /shared'
    - 'CacheDir:  /cache'
    - 'SourceDir: /shared/source'
    - 'RuleDir:   /addon/rules'
    - 'BinDir:    /shared/bin'
    - 'M2Dir:     /cache/m2'
    - Fetching application.
    - '[CMD] Running: /usr/bin/ssh-agent -a /tmp/agent.1'
    - '[CMD] /usr/bin/ssh-agent succeeded.'
    - '[SSH] Agent started.'
    - '[GIT] Cloning: https://github.com/ibraginsky/book-server'
    - '[FILE] Created /addon/.gitconfig.'
    - '[CMD] Running: /usr/bin/git clone --depth 1 https://github.com/ibraginsky/book-server /shared/source/book-server'
    - '[CMD] /usr/bin/git succeeded.'
    - '[RULESET] fetching: id=1 (.discovery)'
    - '[RULESET] fetching: id=20 (.technology-usage)'
    - '[CMD] Running: /usr/bin/windup-shim convert --outputdir /addon/rules/rulesets/1/rules /addon/rules/rulesets/1/rules'
    - '[CMD] /usr/bin/windup-shim succeeded.'
    - '[CMD] Running: /usr/bin/windup-shim convert --outputdir /addon/rules/rulesets/20/rules /addon/rules/rulesets/20/rules'
    - '[CMD] /usr/bin/windup-shim succeeded.'
    - '[CMD] Running: /usr/local/bin/konveyor-analyzer --provider-settings /addon/opt/settings.yaml --output-file /addon/issues.yaml --no-dependency-rules --rules /addon/rules/rulesets/1/rules --rules /addon/rules/rulesets/20/rules --label-selector discovery'
attached:
    - id: 343
      name: ssh-agent.output
      activity: 9
    - id: 344
      name: git.output
      activity: 14
    - id: 345
      name: windup-shim.output
      activity: 18
    - id: 346
      name: windup-shim.output
      activity: 20
    - id: 349
      name: settings.yaml
      activity: 21
    - id: 350
      name: konveyor-analyzer.output
      activity: 22
    - id: 358
      name: pod.yaml
    - id: 359
      name: addon.log
```

### How Reproducible

Always (Default)

### Environment

```markdown
- OS:
```
