### ISSUE TITLE
Enable nightly CI for release branch `release-0.9`

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-ui#2216]
Currently, nightly CI only runs on the main branch.  Investigate what would be required to be able to run a scheduled job that runs CI correctly for a release branch.

Consider:
  - Only workflows in main can run on a cron schedule.
  - Workflows can be invoked on another branch with a call like this:
    ```yml
    on:
      schedule:
        - cron: '0 2 * * *'

    jobs:
      call-workflow:
        uses: konveyor/tackle2-ui/.github/workflows/ci-global.yml@release-0.6
    ```
  - Verify that the `action/checkout` action is pulling the correct ref that matches the branch when/if called as above
  - The __repo CI__ workflows need to be correct for each branch
  - The __E2E CI__ workflows on each branch will then need to know how to:
    - run E2E CI with tests from the correct branch
    - have the test runner install the correct Konveyor version for the branch

This is a followup to #2192
