### ISSUE TITLE
Allow single user mode

### ISSUE THREAD

**Issue by fbladilo** [konveyor/tackle2-ui#63]
We need UI to honor the AUTH_REQUIRED pod environment variable , essentially this will cause Tackle to enable/disable keycloak auth and allow a user to just run as admin without auth. 

When AUTH_REQUIRED is set (false) at the operator level keycloak will not be deployed , so environment variables SSO_* should not be required when AUTH_REQUIRED is set to false.

Also , for naming consistency the SSO_* UI env variables should match what the hub is using : 
```
            - name: KEYCLOAK_REALM
              value: "{{ keycloak_sso_realm }}"
            - name: KEYCLOAK_HOST
              value: "{{ keycloak_sso_host }}"
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ keycloak_sso_hub_client_id }}"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ hub_secret_name }}"
                  key: keycloak_client_secret
```
For reference also see : https://github.com/konveyor/tackle2-operator/issues/33
